/**
 * Train the surrogate: post the exported dataset to the FastAPI backend.
 *
 * WHY THIS IS A SCRIPT AND NOT PART OF THE BACKEND
 * The training data is generated by the verified TypeScript engine, so the
 * natural place to start the loop is where that engine lives. This script is the
 * bridge: it reads the dataset `export-dataset.ts` wrote and hands it to
 * `POST /api/ml/train`, then prints the held-out metrics and whether the model
 * cleared the validation gate.
 *
 * The gate result is printed in full — including a failure. A model that failed
 * is a result worth reporting, and the backend records it either way; what it
 * will not do is serve predictions from it.
 *
 * Run:  npx tsx scripts/train-surrogate.ts
 *       npx tsx scripts/train-surrogate.ts --url http://localhost:8000 --rows 40000
 *       npx tsx scripts/train-surrogate.ts --depth 8 --trees 800 --lr 0.04
 *
 * `--rows N` trains on the first N rows of the exported set, which is how to
 * check how the model behaves as data grows without re-exporting. It is a real
 * result either way: a model that fails the gate is printed with its metrics and
 * recorded, it is just never served.
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = join(here, '..', 'backend', 'data');

function arg(name: string, fallback: string): string {
  const index = process.argv.indexOf(`--${name}`);
  return index >= 0 && process.argv[index + 1] ? process.argv[index + 1]! : fallback;
}

const baseUrl = arg('url', process.env.NEXT_PUBLIC_API_URL ?? 'http://127.0.0.1:8000').replace(
  /\/+$/,
  '',
);
const rowLimit = Number(arg('rows', '0'));

/*
 * Hyperparameters are exposed because the gate is not negotiable and the only
 * honest way to clear it is to fit the physics better. `adaptive_comfort_hours_pct`
 * in particular is a bounded, saturating target — a fraction of hours inside a
 * comfort band — which squared-error boosting underfits at the default depth.
 */
const nEstimators = Number(arg('trees', '400'));
const maxDepth = Number(arg('depth', '6'));
const learningRate = Number(arg('lr', '0.05'));
const testFraction = Number(arg('test', '0.2'));

interface Dataset {
  featureNames: string[];
  targetNames: string[];
  rows: Array<Record<string, number>>;
}

const dataset: Dataset = JSON.parse(
  readFileSync(join(dataDir, 'training-set.json'), 'utf8'),
) as Dataset;

const rows = rowLimit > 0 ? dataset.rows.slice(0, rowLimit) : dataset.rows;

console.log(`\nTraining the surrogate`);
console.log(`  backend   ${baseUrl}`);
console.log(`  dataset   ${rows.length} rows × ${dataset.featureNames.length} features`);
console.log(`  targets   ${dataset.targetNames.join(', ')}`);
console.log(
  `  booster   ${nEstimators} trees, depth ${maxDepth}, lr ${learningRate}, test ${testFraction}\n`,
);

async function main(): Promise<void> {
  /* 1 — Prove the backend is reachable before uploading 1.7 MB. */
  let health: { status?: string; version?: string; engines?: string[] };
  try {
    const response = await fetch(`${baseUrl}/api/health`, {
      signal: AbortSignal.timeout(5000),
    });
    if (!response.ok) throw new Error(`health returned ${response.status}`);
    health = (await response.json()) as typeof health;
  } catch (error) {
    console.error(
      `  Could not reach the backend at ${baseUrl}.\n` +
        `  Start it with:  cd backend && .venv/Scripts/python run.py\n` +
        `  (${error instanceof Error ? error.message : String(error)})\n`,
    );
    process.exitCode = 1;
    return;
  }

  console.log(`  backend up — v${health.version ?? '?'}, engines: ${(health.engines ?? []).join(', ')}\n`);

  /* 2 — Check the feature contract before spending time on a fit. */
  const contract = (await (await fetch(`${baseUrl}/api/ml/contract`)).json()) as {
    featureNames: string[];
    targetNames: string[];
  };

  const mismatch = contract.featureNames.findIndex((name, i) => name !== dataset.featureNames[i]);
  if (mismatch >= 0 || contract.featureNames.length !== dataset.featureNames.length) {
    console.error(
      `  Feature contract mismatch at column ${mismatch}:\n` +
        `    backend has "${contract.featureNames[mismatch] ?? '<end>'}"\n` +
        `    dataset has "${dataset.featureNames[mismatch] ?? '<end>'}"\n` +
        `  Re-run:  npx tsx scripts/export-dataset.ts\n`,
    );
    process.exitCode = 1;
    return;
  }
  console.log('  feature contract matches\n');

  /* 3 — Train. */
  const startedAt = Date.now();
  const response = await fetch(`${baseUrl}/api/ml/train`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
    body: JSON.stringify({
      rows,
      targets: dataset.targetNames,
      nEstimators,
      maxDepth,
      learningRate,
      testFraction,
    }),
    signal: AbortSignal.timeout(300_000),
  });

  const elapsed = ((Date.now() - startedAt) / 1000).toFixed(1);

  if (!response.ok) {
    const detail = await response.text();
    console.error(`  Training failed (${response.status}) after ${elapsed}s:\n  ${detail}\n`);
    process.exitCode = 1;
    return;
  }

  const result = (await response.json()) as {
    modelId: string;
    passedGate: boolean;
    explanation: string;
    targets: Array<{
      target: string;
      metrics: {
        r2: number;
        mae: number;
        rmse: number;
        spearman: number;
        testRows: number;
        gateMinSpearman: number;
        gateMaxMae: number;
      };
      featureImportance: Array<{ feature: string; importance: number }>;
    }>;
  };

  console.log(`  trained in ${elapsed}s   model ${result.modelId}\n`);
  console.log('  target                                  R²     ρ      MAE      RMSE   gate   verdict');
  console.log('  ' + '-'.repeat(90));

  for (const entry of result.targets) {
    const m = entry.metrics;
    const verdict = m.spearman >= m.gateMinSpearman && m.mae <= m.gateMaxMae ? 'PASS' : 'FAIL';
    console.log(
      `  ${entry.target.padEnd(36)}${m.r2.toFixed(4).padStart(7)}${m.spearman
        .toFixed(3)
        .padStart(7)}${m.mae.toFixed(2).padStart(9)}${m.rmse.toFixed(2).padStart(10)}` +
        `${m.gateMinSpearman.toFixed(2).padStart(7)}   ${verdict}`,
    );
  }

  console.log(
    '\n  ρ is Spearman rank correlation — the gate. The optimiser ranks candidates,\n' +
      '  so what matters is that the order agrees with the engine, not that the\n' +
      '  absolute values match a bounded, quantised label. R² is shown for reference.\n',
  );

  console.log(`  ${result.explanation}\n`);

  /* 4 — Show what the model actually learned from, so it is not a black box. */
  const top = result.targets[0]?.featureImportance.slice(0, 6) ?? [];
  if (top.length > 0) {
    console.log(`  What drives ${result.targets[0]!.target}:`);
    for (const entry of top) {
      const bar = '█'.repeat(Math.max(1, Math.round(entry.importance * 40)));
      console.log(`    ${entry.feature.padEnd(32)} ${bar} ${(entry.importance * 100).toFixed(1)}%`);
    }
    console.log('');
  }

  if (!result.passedGate) {
    console.log(
      '  The model was recorded but will NOT serve predictions.\n' +
        '  POST /api/optimize returns 503 until a model clears every target.\n' +
        '  This is deliberate: an unvalidated surrogate is confidently wrong.\n',
    );
    process.exitCode = 1;
    return;
  }

  console.log('  POST /api/optimize is now live — it screens candidates with this model.\n');
}

/* Wrapped rather than using top-level await: tsx emits CommonJS here, which does
   not support it. */
void main();
